name: VPS SSH via GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH, Ngrok, dan Cloudflare Tunnel
        run: |
          set +e

          echo "=== Update paket ==="
          sudo apt-get update --fix-missing

          echo "=== Install paket ==="
          sudo apt-get install -y openssh-server unzip screen curl wget

          # Buat user SSH
          sudo useradd -m github || true
          echo 'github:password123' | sudo chpasswd
          sudo usermod -aG sudo github || true

          # Jalankan SSH Server
          sudo service ssh start || true

          ########## NGROK MODE ##########
          echo "=== Coba Jalankan Ngrok TCP Port 22 ==="
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -o ngrok-v3-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
          ngrok config add-authtoken 31KUHycqX8UtKOVFk8S7Aaz4p1n_6rDfeVbY8yuNGyrFphQ8L

          screen -dmS ngrok22 bash -c "ngrok tcp 22 --log=stdout > ngrok.log 2>&1"
          sleep 5
          HOSTPORT=$(curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[0-9a-zA-Z.:]*' | sed 's/tcp:\/\///')

          ########## FALLBACK CLOUDFLARE ##########
          if [ -z "$HOSTPORT" ]; then
            echo "=== Ngrok gagal, coba Cloudflare Tunnel ==="
            wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared-linux-amd64.deb
            nohup cloudflared tunnel --url tcp://localhost:22 --logfile tunnel.log > /dev/null 2>&1 &
            sleep 8
            HOSTPORT=$(grep -o 'tcp://[0-9a-zA-Z.:]*' tunnel.log | sed 's/tcp:\/\///')
          fi

          if [ -z "$HOSTPORT" ]; then
            echo "❌ Gagal mendapatkan Host & Port!"
            exit 1
          fi

          echo "====================================="
          echo "✅ VPS SSH Aktif!"
          echo "Host & Port : $HOSTPORT"
          echo "Username    : github"
          echo "Password    : password123"
          echo
          echo "Cara konek:"
          echo "ssh github@$(echo $HOSTPORT | cut -d: -f1) -p $(echo $HOSTPORT | cut -d: -f2)"
          echo "====================================="
