name: VPS SSH WebSocket via GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH, Ngrok, dan WebSocket
        run: |
          set +e
          echo "=== Update paket ==="
          sudo apt-get update --fix-missing
          sudo apt-get install -y openssh-server unzip screen curl wget

          # Buat user SSH
          sudo useradd -m github || true
          echo 'github:password123' | sudo chpasswd
          sudo usermod -aG sudo github || true
          sudo service ssh start || true

          # Download install.sh dari Ahmaddevx
          wget -O install.sh https://raw.githubusercontent.com/Ahmaddevx/AHMADDEVXYZ-SSH-Websocket-VPN/main/install.sh

          # Ubah port dari 8098 menjadi 80
          sed -i 's/ahmaddevxyz_websocket.py 8098/ahmaddevxyz_websocket.py 80/' install.sh

          # Jalankan install.sh
          chmod +x install.sh
          sudo ./install.sh

          # Download Ngrok
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -o ngrok-v3-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
          ngrok config add-authtoken 31KUHycqX8UtKOVFk8S7Aaz4p1n_6rDfeVbY8yuNGyrFphQ8L

          # Jalankan Ngrok di port 22
          screen -dmS ngrok22 bash -c "ngrok tcp 22 --log=stdout > ngrok.log 2>&1"
          sleep 5
          HOSTPORT=$(curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[0-9a-zA-Z.:]*' | sed 's/tcp:\/\///')

          if [ -z "$HOSTPORT" ]; then
            echo "❌ Gagal mendapatkan Host & Port!"
            exit 1
          fi

          echo "====================================="
          echo "✅ VPS SSH WS Aktif!"
          echo "Host & Port SSH : $HOSTPORT"
          echo "Username        : github"
          echo "Password        : password123"
          echo "Port WebSocket  : 80"
          echo "====================================="

          # Biar tetap hidup 6 jam penuh
          echo "Menjaga koneksi tetap hidup selama 6 jam..."
          sleep 21600
