name: VPS SSH WebSocket via GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH, Python, dan Ngrok
        run: |
          set +e

          echo "=== Update paket ==="
          sudo apt-get update --fix-missing

          echo "=== Install paket ==="
          sudo apt-get install -y openssh-server python3 python3-pip unzip screen netcat-openbsd curl

          pip3 install websockets

          # Buat user SSH
          sudo useradd -m github || true
          echo 'github:password123' | sudo chpasswd
          sudo usermod -aG sudo github || true

          # Jalankan SSH Server
          sudo service ssh start || true

          # Download Ngrok
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok-v3-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin

          # Token ngrok
          ngrok config add-authtoken 31KUHycqX8UtKOVFk8S7Aaz4p1n_6rDfeVbY8yuNGyrFphQ8L
          # Buat WebSocket listener
          cat << 'EOF' > ws.py
          import asyncio, websockets, subprocess

          async def handler(websocket, path):
              proc = await asyncio.create_subprocess_exec(
                  "nc", "127.0.0.1", "22",
                  stdin=asyncio.subprocess.PIPE,
                  stdout=asyncio.subprocess.PIPE
              )

              async def ws_to_proc():
                  try:
                      async for message in websocket:
                          proc.stdin.write(message.encode())
                          await proc.stdin.drain()
                  except:
                      pass

              async def proc_to_ws():
                  try:
                      while True:
                          data = await proc.stdout.read(1024)
                          if not data:
                              break
                          await websocket.send(data.decode(errors="ignore"))
                  except:
                      pass

              await asyncio.gather(ws_to_proc(), proc_to_ws())

          start_server = websockets.serve(handler, "0.0.0.0", 80)
          asyncio.get_event_loop().run_until_complete(start_server)
          asyncio.get_event_loop().run_forever()
          EOF

          # Jalankan WebSocket
          screen -dmS ws python3 ws.py

          # Jalankan Ngrok TCP port 80
          screen -dmS ngrok80 bash -c "ngrok tcp 80 --log=stdout > ngrok.log 2>&1"

          echo "Menunggu ngrok API aktif..."
          for i in {1..20}; do
            HOSTPORT=$(curl --silent http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[0-9a-zA-Z.:]*' | sed 's/tcp:\/\///')
            if [ ! -z "$HOSTPORT" ]; then
              break
            fi
            sleep 1
          done

          if [ -z "$HOSTPORT" ]; then
            echo "❌ Gagal mendapatkan Host & Port. Log ngrok:"
            cat ngrok.log
            exit 1
          fi

          echo "====================================="
          echo "✅ VPS SSH WS Aktif!"
          echo "Host & Port : $HOSTPORT"
          echo "Username    : github"
          echo "Password    : password123"
          echo
          echo "Payload SSH WS:"
          echo "GET / HTTP/1.1[crlf]Host: $HOSTPORT[crlf]Upgrade: websocket[crlf][crlf]"
          echo "====================================="
